# Generated by Django 4.2.7 on 2024-11-21 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_course_coursetype_coursereservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='adress',
            field=models.CharField(default='Dirección no proporcionada', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(default='666666666', validators=[django.core.validators.MaxValueValidator(999999999), django.core.validators.MinValueValidator(100000000)]),
            preserve_default=False,
        ),
    ]
