# Generated by Django 4.2.7 on 2024-11-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_adress_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='Default.jpg', upload_to='courses'),
            preserve_default=False,
        ),
    ]
