# Generated by Django 4.2.7 on 2024-11-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
