# Generated by Django 4.2.7 on 2024-11-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_course_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
