# Generated by Django 4.2.7 on 2024-11-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customer_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereservation',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Contrarreembolso'), ('PP', 'PayPal'), ('CC', 'Tarjeta')], default='COD', max_length=3),
        ),
    ]
