# Generated by Django 4.2.7 on 2024-11-28 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customer_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_size',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.course'),
        ),
    ]
