# Generated by Django 4.2.7 on 2024-11-28 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_coursereservation_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='capacity',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
